Repository N2-Survey/SurveyFramework, pull requests merged in 2021-11, with the labels that each got.

#38 33 read responses method
  n2survey/lime/survey.py
  tests/test_lime_survey.py
Labels: data import

#48 Templetes for PRs and issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#46 First version of the get_response method of LimeSurvey class.
  n2survey/lime/survey.py
  tests/test_lime_survey.py
Labels: enhancement

#24 17-multiple-choice-plots-function
  n2survey/lime/structure.py
  n2survey/plot/plot_multiple_choice.py
  poetry.lock
  pyproject.toml
Labels: plots

#52 First bar plot
  n2survey/__init__.py
  n2survey/lime/survey.py
  n2survey/plot/__init__.py
  n2survey/plot/bar.py
Labels: plots

#53 Updated plot_multiple_choice module
  n2survey/lime/survey.py
  n2survey/plot/__init__.py
  n2survey/plot/plot_multiple_choice.py
Labels: plots
