Repository N2-Survey/SurveyFramework, pull requests merged in 2022-03, with the labels that each got.

#87 84 Filter by question before counting/plotting
  n2survey/lime/survey.py
  tests/test_lime_survey.py
Labels: enhancement

#95 94 change default filename for comp plots
  n2survey/lime/survey.py
  n2survey/plot/simple_comparison.py
Labels: bug, plots

#82 75-Mental-health-transformations
  n2survey/lime/survey.py
  tests/test_lime_survey.py
Labels: enhancement

#98 readded the, for what ever reason, by me removed theme variable
  n2survey/lime/survey.py
  n2survey/plot/simple_comparison.py
Labels: bug

#73 69 Helper functions for exporting and importing aggregate data
  n2survey/lime/survey.py
Labels: enhancement

#100 added your solution to the code, now it seems to work
  n2survey/plot/simple_comparison.py
Labels: bug
